### ISSUE TITLE
Fps

### ISSUE THREAD

**Issue by poudyalbot** [KopiSoftware/VINS_Lite_GPU#2]
At what fps does it run in jetson nano.
Thank you

**Comment by KopiSoftware** [comment]
@poudyalbot Good question, I forgot to post the runtime performance. Regardless of the tracking image view, it can be very easy to  reach 30fps on Jetson Nano 2GB with half feature number cut down. The feature tracking image view somehow always delays seriously, but if you check the pose_graph from RVIZ, you'll find that the estimated location of VINS is real-time. Running in the MONO mode is also a good choice if you want to run multiple programs on one device at the same time.

Here is my configruation:
```yaml
multiple_thread: 4
max_cnt: 75
freq: 30                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation.
max_solver_time: 0.02  # max solver itration time (ms), to guarantee real time
max_num_iterations: 4   # max solver itrations, to guarantee real time
```
